config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  post 'searches/create'
  post 'searches/good'
  post 'searches/destroy'

  get 'tests/index'
  get 'tests/game'
  get 'tests/modal'

  get 'home/index'
  get 'translation/index'
  get 'typings/index'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/translation.rb
class Translation < ApplicationRecord
end

app/models/typing.rb
class Typing < ApplicationRecord
    # 漢字変換
    # 参考 => https://qiita.com/Naggi-Goishi/items/e9f8753e88bc9f0b67b5
    def to_hiragana()
        begin
          # pタグの部分を抽出
          Mechanize.new.get('https://yomikatawa.com/kanji/' + self.word).search('#content p').first.inner_text
        rescue => exception
          # 漢字ではなかった場合、そのまま返す
          return self.word
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # ウィキペディア
  # 参考 => https://github.com/kenpratt/wikipedia-client
  require 'wikipedia'

  def index
    @results = Search.all
  end

  def create
    text = params[:keyword].split(/\r\n|\r|\n/);
    if text.instance_of?(Array) # 複数の単語
      text.each do |word|
        wiki_search(word)
      end
    else
      wiki_search(text) # 一つの単語
    end
    @results = Search.all
  end

  def good
    @searche = Search.find(params[:id])
    @searche.title = "1"
    if @searche.save
      @results = Search.all
    end
  end

  def destroy
    @searche = Search.find(params[:id])
    @searche.title = "0"
    if @searche.save
      @results = Search.all
    end
  end

  private
  def wiki_search(word)
    if Wikipedia.find(word).summary
        word = Wikipedia.find(word).summary
        @results = Search.new(content: word)
    else
        url = "https://www.google.com/search?q=" + word
        @results = Search.new(url: url)
    end
    @results.save
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  # ウィキペディア
  # 参考 => https://github.com/kenpratt/wikipedia-client
  require 'wikipedia'

  def index
    # @test = Test.all
    if params[:keyword]
      @results = Wikipedia.find(params[:keyword]).summary
    else
      @results = Wikipedia.find(".")
    end
  end

  def game
  end

  def vue
  end
end

app/controllers/translation_controller.rb
class TranslationController < ApplicationController
  
  require 'natto'
  require "open-uri" #webに接続するためのライブラリ
  require "nokogiri" #クレイピングに使用するライブラリ

  def index
    text = 'ななみちゃんは、今何してるの？
    おじさんはななみちゃんとのデートの事を考えてるよ！
    ダメだなしっかりしろ、俺'
    nm = Natto::MeCab.new
    @text = []
    array = ["ぴえん", "えぐいって", "全集中の呼吸", "淡色系女子", "あっ…察し", "パクツイ", "３１５０", "パリピ", "かまちょ", "ぱおん", "すきぴ",
    "ジワる",  "エゴサ", "ワッショイ", "きゅんです", "エモい", "ぽよ", "エチエチ", "ンゴ", "すこ", "きゅんきゅん", "よき", "しごおわ", "ふぁぼ",
    "らぶりつ"]
    tem = ""

    # テスト用
    @text_origin = []
    @part = []

    nm.parse(text) do |n|
      # 判定
      if n.feature.first(10).include?('係助詞')
        @text.push("#{n.surface}、")
        tem = '読点'
      elsif n.feature.first(10).include?('読点')
        if tem == '読点'
          tem = 0
        else
          @text.push(n.surface)
          tem = '読点'
        end
      else
        @text.push(n.surface)
        tem = 0
      end

      # テスト用
      @text_origin.push(n.surface) # 元の文章
      @part.push(n.feature) # 形態素解析の文章
    end
  end
end

app/controllers/typings_controller.rb
class TypingsController < ApplicationController
  require 'romkan' # ひらがな　=> ローマ字
  require 'mechanize' # スクレイピング

  def index
    @problem_ja = []
    @problem_ro = []

    # データベースから単語を持ってくる
    @typing_words = Typing.all
    @typing_words.each do |words|
      @problem_ja.push(words.word) # 日本語を追加
      @problem_ro.push(words.to_hiragana.to_roma) # ローマ字を追加
    end
    @rand = rand(@problem_ja.length)

    # railsの変数をjsでも使用可能にする
    gon.problem_ja = @problem_ja
    gon.problem_ro = @problem_ro
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/translation_helper.rb
module TranslationHelper
end

app/helpers/typings_helper.rb
module TypingsHelper
end

app/views/home/index.html.erb
<div style="text-align:center;">
    <h2><%= link_to "形態素解析", translation_index_path %></h2>
    <h2><%= link_to "タイピング", typings_index_path %></h2>
    <h2><%= link_to "Wikipedia 検索", searches_index_path %></h2>
    <h2><%= link_to "お試し　テスト", tests_index_path %></h2>
    <h2><%= link_to "お試し　ゲーム", tests_game_path %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <div class="container" style="width: 70%; margin: 0 auto; text-align:center;">
      <h1 id="title-header" style="width: 50%; margin:50px auto; padding: 20px;"><%= link_to "rails　練習", root_path %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with url: searches_create_path, local: false do |f| %>
  <%= f.text_area :keyword %>
  <%= f.submit 'Search' %>
<% end %>

app/views/searches/_show.html.erb
<div id="ajax-test">
    <% if results %>
        <% results.each do |result| %>
            <h4 style="border-top: 1px solid; padding: 20px 50px; margin:0;"><%= result.content %></h4>
            <% if (result.title === "1") %>
                <%= link_to searches_destroy_path(id: result.id), method: :post, remote: true do %>
                    <i id="icon-good" class="fas fa-heart fa-2x" style="color: red;"></i>
                    <%= result.title %>
                <% end %>
            <% else %>
                <%= link_to searches_good_path(id: result.id), method: :post, remote: true do %>
                    <i id="icon-good" class="far fa-heart fa-2x" style="color: red;"></i>
                    <%= result.title %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/searches/create.js.erb
$("#ajax-test").html("<%= j(render 'searches/show', results: @results ) %>");
$(".title").text("ajax実行")
$(".title").css("color", "red")
$("textarea").val("");

app/views/searches/destroy.js.erb
$("#ajax-test").html("<%= j(render 'searches/show', results: @results ) %>");

app/views/searches/good.js.erb
$("#ajax-test").html("<%= j(render 'searches/show', results: @results ) %>");

app/views/searches/index.html.erb
<h1>Wikipedia 検索</h1>
<div class="form-area my-5">
    <%= render partial: 'form' %>
</div>

<h1 class="title m-5">検索結果</h1>
<%= render partial: 'show', locals: { results: @results } %>

app/views/translation/index.html.erb
<div style="margin: 0 auto; text-align: center;">
    <h1>形態素解析　練習</h1>

    <div style="margin-top: 100px;">
    <%# テスト %>
<%
=begin 
%>
        <% @text.zip(@part) do |text, part| %>
            <% if part == '助詞' %>
                <%= text + '、' %>
            <% else %>
                <%= text %>
            <% end %>
        <% end %>
<%
=end 
%>
        <%= @text_origin.join() %>
        <h3><br>↓↓</h3><br>
        <%= @text.join('') %>
        <h3><br>ーーーーー</h3><br>
        <%= @part %>
    </div>
</div>

app/views/translation/key.html.erb
<div style="margin: 0 auto; text-align: center;">
    <h1 id="idname">キー判定　練習</h1>

    <h1>タイピング</h1>

    <h3 id="problem_ja"><%= @problem_ja[@rand] %></h3>
    <h3 id="problem_ro"><%= @problem_ro[@rand] %></h3>
    <h3 id="key_test" style="border:2px solid black; height:30px; width:40%; margin: 0 auto;"></h3><br>
    <h3 id="judge"></h3><br>
    <button id="reset_btn">リセット</button>
</div>

<%# gem gonの使用 %>
<%= include_gon %>
<%# javascript使用 %>
<%= javascript_pack_tag 'key' %>

app/views/typings/index.html.erb
<div style="margin: 0 auto; text-align: center;">
    <h1 id="idname">キー判定　練習</h1>

    <h1>タイピング</h1>

    <h3 id="problem_ja"><%= @problem_ja[@rand] %></h3>
    <h3 id="problem_ro"><%= @problem_ro[@rand] %></h3>
    <h3 id="key_test" style="border:2px solid black; height:30px; width:40%; margin: 0 auto;"></h3><br>
    <h3 id="judge"></h3><br>
    <button id="reset_btn">リセット</button>
</div>

<%# gem gonの使用 %>
<%= include_gon %>
<%# javascript使用 %>
<%= javascript_pack_tag 'key' %>